import {readFileSync} from 'node:fs';
import {serverlessBrowser} from '../vet/serverless-browser.mjs';
const logo=readFileSync(new URL('../../public/branding/hsp-logo-aubergine.svg',import.meta.url),'utf8').replace(/<\?xml[^>]*>/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function renderConsolidated(d,locale,m,{browser:provided}={}){
 const browser=provided??await serverlessBrowser.launch();let page;
 try{
  page=await browser.newPage({javaScriptEnabled:false});await page.route('**/*',r=>r.abort());
  const s=d.snapshot,t=m.t;
  const header=`<header><div class="logo">${logo}</div><div><h1>${esc(m.title)}</h1><div>${esc(t.accountNumber)} : <strong>${esc(s.account_number)}</strong></div>${d.number?`<div>${esc(d.kind==='receipt'?t.receiptNumber:t.invoiceNumber)} : ${esc(d.number)}</div>`:''}<div>${esc(s.context[locale==='fr'?'name_fr':'name_en'])} · ${esc(m.issued)}</div></div></header><div class="demo">${esc(t.demo)}</div><div class="reminder">${esc(m.reminder).replaceAll('\n','<br>')}</div>`;
  await page.setContent(`<!doctype html><html lang="${locale}"><meta charset="utf-8"><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;color:#26212a;font:12px Arial,sans-serif}.page{height:272mm;display:flex;flex-direction:column;break-after:page}.page:last-child{break-after:auto}header{display:flex;gap:16px;align-items:center;font-size:11px;line-height:1.4}h1{font-size:21px;margin:0 0 5px;color:#653c59}.logo{width:72px;flex-shrink:0}.logo svg{width:100%;height:auto}.demo{font-size:10px;background:#f4edf2;padding:5px;margin-top:7px;font-weight:bold}.reminder{font-size:11px;line-height:1.3;padding:7px;border:1px solid #653c59;margin:6px 0;font-weight:bold}.body{flex:1;overflow:hidden}.payer{font-size:11px;margin:6px 0}.consolidation{font-size:11px;line-height:1.3;margin:6px 0}table{width:100%;border-collapse:collapse;table-layout:fixed;margin:0 0 8px}td,th{padding:5px;vertical-align:top;border-bottom:1px solid #ddd;white-space:pre-line;overflow-wrap:anywhere}th{text-align:left;background:#f4edf2;font-size:11px}.group th{background:white;color:#653c59;font-size:14px;padding:9px 5px 5px}.identifier th{font-size:11px;background:white}.notice th{background:#f4edf2;font-size:11px;line-height:1.25}td:not(:first-child),thead tr.columns th:not(:first-child){text-align:right;font-variant-numeric:tabular-nums}tr.total{font-weight:bold}.summary td{font-size:20px;font-weight:bold;padding:7px;background:#f4edf2}.summary .group th{font-size:16px}.summary thead tr.columns{display:none}footer{padding-top:6px;font-size:10px;border-top:1px solid #ccc;display:flex;justify-content:space-between}</style><body></body></html>`);
  await page.evaluate(({header,blocks,continued,payer,consolidation,account})=>{
   let body,table,tb;const pages=[];
   function newPage(first=false){const p=document.createElement('section');p.className='page';p.innerHTML=header+'<div class="body"></div><footer></footer>';document.body.append(p);body=p.querySelector('.body');if(first){const b=document.createElement('div');b.className='payer';b.textContent=payer;body.append(b);}pages.push(p);}
   function newTable(b,cont){table=document.createElement('table');table.className=b.kind??'';table.dataset.supplier=b.supplier??'';const compact=b.kind==='supplierTotals'&&Array.from(body.querySelectorAll('table.supplier')).some(x=>x.dataset.supplier===b.supplier);const cg=document.createElement('colgroup');for(let i=0;i<2;i++){const col=document.createElement('col');col.style.width=i===0?'70%':'30%';cg.append(col);}table.append(cg);const h=table.createTHead();for(const [cls,value] of [['group',b.label+(cont?' — '+continued:'')],['identifier',b.identifier],['notice',b.notice]]){if(!value||compact)continue;const row=h.insertRow();row.className=cls;const th=document.createElement('th');th.colSpan=2;th.textContent=value;row.append(th);}const row=h.insertRow();row.className='columns';for(const c of b.columns){const th=document.createElement('th');th.textContent=c;row.append(th);}tb=table.createTBody();body.append(table);}
   function addRow(b,values,i){const row=tb.insertRow();if(b.boldRows?.includes(i))row.className='total';for(const v of values)row.insertCell().textContent=v;return row;}
   newPage(true);
   for(const b of blocks){newTable(b,false);if(b.kind==='supplierTotals'&&b.rows.length<=8){b.rows.forEach((v,i)=>addRow(b,v,i));const overflow=body.scrollHeight>body.clientHeight;tb.innerHTML='';if(overflow){table.remove();newPage();newTable(b,true);}}for(let i=0;i<b.rows.length;i++){let row=addRow(b,b.rows[i],i);if(body.scrollHeight>body.clientHeight){row.remove();if(!tb.rows.length)table.remove();newPage();newTable(b,i>0);row=addRow(b,b.rows[i],i);if(body.scrollHeight>body.clientHeight)throw Error('BILLING_PDF_ROW_TOO_LARGE');}}if(b.kind==='summary'&&consolidation){const p=document.createElement('p');p.className='consolidation';p.textContent=consolidation;body.append(p);if(body.scrollHeight>body.clientHeight){p.remove();newPage();body.append(p);}}}
   pages.forEach((p,i)=>{p.querySelector('footer').innerHTML='';const a=document.createElement('span'),b=document.createElement('span');a.textContent=account;b.textContent=`${i+1} / ${pages.length}`;p.querySelector('footer').append(a,b);});
  },{header,blocks:m.blocks,continued:m.continued,payer:[s.payer.first_name,s.payer.last_name,s.payer.company_name].filter(Boolean).join(' '),consolidation:d.kind==='receipt'?'':m.consolidation,account:`${t.accountNumber} : ${s.account_number}`});
  return await page.pdf({preferCSSPageSize:true,printBackground:true});
 }finally{await page?.close();if(!provided)await browser.close();}
}
