// Isolated UX preview with in-memory fake RPC/Stripe responses. No DB or Stripe traffic.
import {createServer} from 'vite';
import {mkdirSync,writeFileSync} from 'node:fs';
let seq=1,version=1,ready=false,closed=false,pending=null;const charges=[{id:'charge-1',description:'Stalle simulée',quantity:1,unit_price:100,subtotal:100,tax_amount:0,total:100,taxes:[],beneficiary:{display_name:'Faux Payeur'},horse:{name:'Cheval fictif'}}],payments=[],documents=[],commands=new Map();
const payer={customer_account_id:'customer-demo',first_name:'Faux',last_name:'Payeur',company_name:'Entreprise fictive',address:'Adresse fictive'};
const total=()=>charges.reduce((sum,c)=>sum+c.total,0),balance=()=>total()-payments.reduce((sum,p)=>sum+p.amount,0);
const snapshot=()=>({account_number:'DEMO-2026-00001',folio_id:'folio-demo',state:closed?'closed':'open',currency:'CAD',context:{id:'context-demo',name_fr:'Concours fictif',name_en:'Fictitious show',financial_year:2026},payer,charges:structuredClone(charges),payments:structuredClone(payments),subtotal:total(),tax_amount:0,total:total(),received:total()-balance(),balance:balance()});
function doc(kind){const d={id:'doc-'+(++seq),kind,number:kind==='statement'?null:`DEMO-${kind}-${seq}`,snapshot:{...snapshot(),...(kind==='receipt'?{receipt_payment:structuredClone(payments.at(-1))}:{})},created_at:new Date().toISOString()};documents.push(d);return d;}
function rpc(name,a){switch(name){
case 'billing_ui_detail':return {...snapshot(),documents,checkout:{ready,version,can_prepare:ready&&!balance()&&!pending&&!closed,reasons:closed?['CLOSED']:!ready?['FEES_EXPECTED']:balance()?['BALANCE_DUE']:['RECAP_REQUIRED']},stripe:{can_pay:!closed&&balance()>0,available:balance()-(pending?.amount??0),reserved:pending?.amount??0,attempt:pending},actions:a.p_personal?{}:{sale:!closed,payment:!closed,attest:!closed,finalize:!closed}};
case 'billing_ui_catalog':return {enabled:true,context_id:'context-demo',currency:'CAD',products:[{id:'product-demo',name:'Vente fictive',price:50}]};
case 'billing_get_customer_account':return 'customer-demo';
case 'add_billing_sale':if(closed)throw Error('BILLING_FOLIO_CLOSED');if(commands.has(a.p_request_id))return commands.get(a.p_request_id);charges.push({...charges[0],id:'charge-'+(++seq),unit_price:50,subtotal:50,total:50});version++;ready=false;commands.set(a.p_request_id,{});return {};
case 'list_billing_contexts':return {total:1,items:[{id:'context-demo',show_id:'show-demo',name_fr:'Concours fictif',name_en:'Fictitious show',year:2026,currency:'CAD',accounts:1,open_accounts:closed?0:1,total:total(),paid:total()-balance(),balance:balance()}]};
case 'list_billing_accounts':case 'list_my_billing_accounts':case 'search_billing_finance':return {total:1,items:[{id:'folio-demo',kind:'show_account',account_number:'DEMO-2026-00001',year:2026,state:closed?'closed':'open',payer,currency:'CAD',total:total(),paid:total()-balance(),balance:balance()}]};
case 'get_billing_finance_overview':return {has_data:true,groups:[{currency:'CAD',subtotal:total(),tax_amount:0,paid:total()-balance(),balance:balance(),open_accounts:closed?0:1,closed_accounts:closed?1:0,needs_attention:0}]};
case 'billing_set_ready':ready=a.p_ready;return {};
case 'billing_set_close_block':ready=false;return {};
case 'record_billing_payment':{if(commands.has(a.p_request_id))return commands.get(a.p_request_id);const amount=Number(a.p_payment.amount);if(amount>balance()-(pending?.amount??0))throw Error('BILLING_PAYMENT_RESERVED');payments.push({id:'payment-'+(++seq),amount,method:a.p_payment.method,received_at:new Date().toISOString(),allocations:a.p_payment.allocations});version++;const r={document:doc('receipt')};commands.set(a.p_request_id,r);return r;}
case 'get_billing_statement':case 'prepare_own_billing_recap':{const d=doc('statement');return {document:d,document_id:d.id,version,account:{version}};}
case 'finalize_billing_folio':case 'finalize_own_billing_folio':{if(commands.has(a.p_request_id))return commands.get(a.p_request_id);if(pending||closed||a.p_version!==version||(name==='finalize_own_billing_folio'&&(!ready||balance())))throw Error('BILLING_NOT_ADMISSIBLE');closed=true;const r={document:doc('invoice')};commands.set(a.p_request_id,r);return r;}
default:throw Error('BILLING_PREVIEW_UNSUPPORTED');}}
function payment(a){if(a.action==='begin'){if(pending)throw Error('BILLING_PENDING_PAYMENT');const amount=Number(a.amount);if(amount<=0||amount>balance())throw Error('BILLING_INVALID_AMOUNT');pending={id:'attempt-'+(++seq),state:'requires_confirmation',amount,resolved:false};return {attempt_id:pending.id,state:pending.state,publishable_key:'pk_test_mock',client_secret:'mock_only'};}if(!pending)throw Error('BILLING_PENDING_PAYMENT');if(a.action==='cancel'){pending=null;return {state:'canceled'};}payments.push({id:'payment-'+(++seq),amount:pending.amount,method:'stripe_test',received_at:new Date().toISOString(),allocations:[]});version++;doc('receipt');pending=null;return {state:'succeeded'};}
mkdirSync('.tmp/billing-ui',{recursive:true});writeFileSync('.tmp/billing-ui/preview.html',`<html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><p style="padding:1rem">APERÇU UX — API et Stripe simulés en mémoire, aucune base ou API externe. <a href="/associations/org-demo/finance">Administration</a> · <a href="/me/accounts">Payeur</a></p><div id="root"></div><script>window.Stripe=()=>({elements:()=>({create:()=>({mount:n=>n.innerHTML='<p>Payment Element SIMULÉ — aucune carte réelle</p>',destroy:()=>{}})}),confirmPayment:async()=>({})});</script><script type="module" src="/scripts/billing/finance-harness.tsx"></script></body></html>`);
const server=await createServer({configFile:false,define:{'import.meta.env.VITE_SUPABASE_URL':JSON.stringify('http://127.0.0.1:5318'),'import.meta.env.VITE_SUPABASE_ANON_KEY':JSON.stringify('preview-mock-public')},server:{host:'127.0.0.1',port:5318,strictPort:true},plugins:[{name:'local-preview',configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url?.startsWith('/rest/v1/rpc/')||req.url==='/__local-billing/payment'){try{let raw='';for await(const part of req)raw+=part;if(raw.length>10000)throw Error('BILLING_INVALID_REQUEST');const a=JSON.parse(raw),value=req.url==='/__local-billing/payment'?payment(a):rpc(req.url.split('/').at(-1),a);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value));}catch(e){res.statusCode=400;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({error:e.message,message:e.message}));}return;}if(req.url==='/'||req.url?.startsWith('/associations/')||req.url?.startsWith('/me/'))req.url='/.tmp/billing-ui/preview.html';next();});}}]});await server.listen();console.log('UX preview (MOCKS): http://127.0.0.1:5318/');
