import {serverlessBrowser as chromium} from '../../server/vet/serverless-browser.mjs';
import {createServer} from 'vite';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync('.tmp/billing-ui',{recursive:true});
writeFileSync('.tmp/billing-ui/results.json',JSON.stringify({complete:false,mode:'browser mocks',passed:[]}));
writeFileSync('.tmp/billing-ui/index.html','<html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module" src="/scripts/billing/finance-harness.tsx"></script></body></html>');
const vite=await createServer({configFile:false,define:{'import.meta.env.VITE_SUPABASE_URL':JSON.stringify('http://127.0.0.1:54321'),'import.meta.env.VITE_SUPABASE_ANON_KEY':JSON.stringify('test-only-public-placeholder')},server:{host:'127.0.0.1',port:5317,strictPort:true},plugins:[{name:'fixture-paths',configureServer(s){s.middlewares.use((req,res,next)=>{if(req.url?.startsWith('/me/')||req.url?.startsWith('/associations/'))req.url='/.tmp/billing-ui/index.html';next();});}}]});await vite.listen();
const browser=await chromium.launch({headless:true});let complete=false;const passed=[];
try{
 const page=await browser.newPage({viewport:{width:1365,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 let injectError=false,lostSale=false,lostPayment=false;const paymentRequests=new Map(),stripeRequests=new Map();const commands=new Map();let seq=0,version=1,ready=false,closed=false,pending=null;const payments=[],documents=[],charges=[charge(100)];
 function charge(n){return {id:'charge-'+(++seq),description:'Stalle simulée',quantity:1,unit_price:n,subtotal:n,tax_amount:0,total:n,currency:'CAD',beneficiary:{contact_id:'contact-demo',display_name:'Faux Payeur'},horse:{id:'horse-demo',name:'Cheval fictif'},taxes:[],exemption_reason:'Fictif'};}
 const balance=()=>charges.reduce((s,c)=>s+c.total,0)-payments.reduce((s,p)=>s+p.amount,0);
 function snapshot(){return {folio_id:'folio-demo',account_number:'DEMO-2026-00001',state:closed?'closed':'open',currency:'CAD',context:{id:'context-demo',name_fr:'Concours fictif',name_en:'Fictitious show',financial_year:2026,year_basis:'show_start'},payer:{customer_account_id:'customer-demo',contact_id:'contact-demo',first_name:'Faux',last_name:'Payeur',address:'Adresse fictive'},charges:structuredClone(charges),payments:structuredClone(payments),subtotal:charges.reduce((s,c)=>s+c.total,0),tax_amount:0,total:charges.reduce((s,c)=>s+c.total,0),received:payments.reduce((s,p)=>s+p.amount,0),balance:balance()};}
 function document(kind){const d={id:'doc-'+(++seq),kind,number:kind==='statement'?null:`DEMO-${kind}-${seq}`,snapshot:{...snapshot(),...(kind==='receipt'?{receipt_payment:structuredClone(payments.at(-1))}:{})},created_at:new Date().toISOString()};documents.push(d);return d;}
 let pdfState='pending';
 await page.route('**/__local-billing-documents/**',async route=>{const a=route.request().postDataJSON();assert.equal(typeof a.personal,'boolean');if(route.request().url().endsWith('/download')){await route.fulfill({contentType:'application/pdf',body:readFileSync('.tmp/billing-pdf/invoice-fr.pdf')});return;}if(route.request().url().endsWith('/retry'))pdfState='completed';await route.fulfill({contentType:'application/json',body:JSON.stringify({state:pdfState,locales:pdfState==='completed'?['fr','en']:[],retry_at:null})});});
 await page.route('**/rest/v1/rpc/**',async route=>{const name=route.request().url().split('/').at(-1),args=route.request().postDataJSON();if(injectError&&name==='billing_ui_detail'){await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'BILLING_PROVIDER_RETRY'})});return;}let data;
 switch(name){
 case 'billing_ui_detail':data={...snapshot(),documents,checkout:{ready,version,can_prepare:ready&&balance()===0&&!closed&&!pending,reasons:closed?['CLOSED']:!ready?['FEES_EXPECTED']:balance()?['BALANCE_DUE']:['RECAP_REQUIRED']},stripe:{can_pay:!closed,reserved:pending?.amount??0,available:balance()-(pending?.amount??0),attempt:pending},actions:args.p_personal?{}:{sale:!closed,payment:true,attest:!closed,finalize:!closed}};break;
 case 'list_horse_health_compliance':data=[];break;
 case 'billing_navigation_scope':data={staff:true};break;
 case 'get_billing_finance_overview':data={groups:[],has_data:false};break;
 case 'list_billing_contexts':data={total:1,items:[{id:'context-demo',show_id:'show-demo',name_fr:'Concours fictif',name_en:'Fictitious show'}]};break;
 case 'billing_ui_catalog':data={enabled:true,context_id:'context-demo',currency:'CAD',products:[{id:'product-demo',name:'Stalle simulée',price:50}]};break;
 case 'list_my_billing_accounts':case 'list_billing_accounts':data={total:1,items:[{id:'folio-demo',account_number:'DEMO-2026-00001',year:2026,currency:'CAD',state:closed?'closed':'open',payer:snapshot().payer,balance:balance()}]};break;
 case 'add_billing_sale':if(commands.has(args.p_request_id)){data=commands.get(args.p_request_id);break;}charges.push(charge(50));version++;ready=false;data={};commands.set(args.p_request_id,data);if(lostSale){lostSale=false;await route.abort();return;}break;
 case 'record_billing_payment':{
 if(paymentRequests.has(args.p_request_id)){assert.deepEqual(args,paymentRequests.get(args.p_request_id));data={};break;}
 assert.equal(args.p_payment.version,version);paymentRequests.set(args.p_request_id,structuredClone(args));payments.push({id:'manual-'+(++seq),...args.p_payment});version++;document('receipt');data={};if(lostPayment){lostPayment=false;await route.abort();return;}break;}
 case 'billing_set_ready':ready=args.p_ready;data={};break;
 case 'get_billing_statement':case 'prepare_own_billing_recap':data={document:document('statement'),version,account:{version}};data.document_id=data.document.id;break;
 case 'finalize_own_billing_folio':case 'finalize_billing_folio':assert(ready&&balance()===0&&!pending);closed=true;data={document:document('invoice')};break;
 default:errors.push('Unexpected mocked RPC '+name);data=[];
 }
 await route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
 });
 await page.route('https://js.stripe.com/v3/',route=>route.fulfill({contentType:'text/javascript',body:`window.Stripe=()=>({elements:()=>({create:()=>({mount:n=>{n.innerHTML='<label>Carte Stripe TEST (mock)<input aria-label="Carte Stripe TEST (mock)" value="4242"></label>'},destroy:()=>{}})}),confirmPayment:async()=>({})});`}));
 await page.route('**/__local-billing/payment',async route=>{const b=route.request().postDataJSON();let result;
 if(b.action==='begin'){
 if(stripeRequests.has(b.request_id)){result=stripeRequests.get(b.request_id);}
 else{pending={id:'attempt-'+(++seq),state:'requires_confirmation',amount:Number(b.amount),resolved:false};result={attempt_id:pending.id,state:pending.state,client_secret:'mock_secret',publishable_key:'pk_test_mock'};stripeRequests.set(b.request_id,result);}
 }else{assert(pending);const id=pending.id;
 if(b.action==='cancel'){result={attempt_id:id,state:'canceled'};}
 else{payments.push({id:'payment-'+(++seq),method:'stripe_test',amount:pending.amount,received_at:new Date().toISOString(),allocations:[]});version++;document('receipt');result={attempt_id:id,state:'succeeded'};}
 for(const [key,value] of stripeRequests)if(value.attempt_id===id)stripeRequests.set(key,result);
 pending=null;
 }await route.fulfill({contentType:'application/json',body:JSON.stringify(result)});});

 async function go(path){await page.goto('http://127.0.0.1:5317'+path);await page.getByRole('heading').first().waitFor();}
 async function sale(){await page.getByLabel('Produit — prix du contexte').selectOption('product-demo');await page.getByRole('button',{name:'Ajouter le frais',exact:true}).click();await page.waitForTimeout(150);}
 async function pay(amount){await page.getByLabel('Montant partiel ou solde').fill(String(amount));await page.getByRole('button',{name:'Payer mon compte — TEST',exact:true}).click();await page.getByLabel('Carte Stripe TEST (mock)').waitFor();const confirmed=page.waitForResponse(r=>r.url().includes('/__local-billing/payment')&&r.request().postDataJSON().action==='resume');await page.getByRole('button',{name:'Confirmer le paiement test',exact:true}).click();await confirmed;await page.waitForTimeout(150);}
 await go('/associations/org-demo/finance/accounts/folio-demo');await sale();assert.equal(charges.length,2);passed.push('secretary adds simulated stall to common account');
 await go('/me/accounts?year=all');await page.getByRole('button',{name:'Ouvrir',exact:true}).click();await pay(40);assert.equal(payments.length,1);passed.push('payer list/detail and first partial payment through mocked Element/service');
 await go('/associations/org-demo/finance/accounts/folio-demo');await sale();await go('/me/accounts/folio-demo');await pay(balance());assert.equal(payments.length,2);await page.getByRole('button',{name:/Reçu de paiement/}).last().click();await page.getByText(/Paiement de ce reçu/).waitFor();passed.push('new charge then second payment and two receipts');
 await go('/associations/org-demo/finance/accounts/folio-demo');await page.getByRole('button',{name:'Attester : tous les frais attendus sont ajoutés',exact:true}).click();await page.waitForTimeout(150);
 await page.screenshot({path:'.tmp/billing-ui/admin-desktop.png',fullPage:true});
 await go('/me/accounts/folio-demo');await page.getByRole('button',{name:'Vérifier le récapitulatif de fermeture',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'Retour');
 await page.getByRole('button',{name:'Finaliser mon compte',exact:true}).click();await page.waitForTimeout(150);assert.equal(documents.filter(d=>d.kind==='invoice').length,1);passed.push('versioned dialog focus and one final invoice');
 await page.reload();await page.getByRole('button',{name:/Facture finale/}).click();await page.getByText(/Génération en attente/).waitFor();assert.equal(documents.filter(d=>d.kind==='invoice').length,1);passed.push('direct route/reload reads immutable document without another invoice');
 await page.screenshot({path:'.tmp/billing-ui/payer-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await go('/me/accounts?year=all');await page.screenshot({path:'.tmp/billing-ui/payer-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));passed.push('mobile account list without page overflow');
 await go('/me/accounts/folio-demo?lang=en');await page.getByRole('button',{name:/Final invoice/}).waitFor();passed.push('English detail');
 injectError=true;await go('/me/accounts/folio-demo');await page.getByRole('alert').waitFor();injectError=false;await page.getByRole('button',{name:'Réessayer',exact:true}).click();await page.getByRole('button',{name:/Facture finale/}).waitFor();passed.push('load error is distinct and retry restores detail');
 await page.goBack();await page.getByRole('button',{name:/Final invoice/}).waitFor();passed.push('browser back restores URL language and account');
 closed=false;ready=false;await go('/associations/org-demo/finance/accounts/folio-demo');const before=charges.length;lostSale=true;await page.getByLabel('Produit — prix du contexte').selectOption('product-demo');await page.getByRole('button',{name:'Ajouter le frais',exact:true}).click();await page.getByRole('alert').waitFor();await page.reload();await page.getByRole('button',{name:'Résoudre la commande précédente',exact:true}).click();await page.waitForTimeout(250);assert.equal(charges.length,before+1);passed.push('sale response lost then reload/retry reuses durable command');
 await go('/me/accounts/folio-demo');await page.getByLabel('Montant partiel ou solde').fill('10');await page.getByRole('button',{name:'Payer mon compte — TEST',exact:true}).click();await page.getByLabel('Carte Stripe TEST (mock)').waitFor();const canceledKey=[...stripeRequests.keys()].at(-1);await page.getByRole('button',{name:'Annuler auprès de Stripe',exact:true}).click();await page.waitForTimeout(150);await page.reload();const paidBefore=payments.length;await pay(10);assert.equal(payments.length,paidBefore+1);assert.notEqual([...stripeRequests.keys()].at(-1),canceledKey);passed.push('server-confirmed cancellation then reload and same amount uses new key and one payment');
 await go('/associations/org-demo/finance/accounts/folio-demo');const manualBefore=payments.length,receiptBefore=documents.filter(d=>d.kind==='receipt').length;lostPayment=true;await page.getByLabel('Montant partiel ou solde').fill('5');await page.getByRole('button',{name:'Confirmer la réception fictive',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(payments.length,manualBefore+1);await page.reload();await page.getByRole('button',{name:'Résoudre la commande précédente',exact:true}).click();await page.waitForTimeout(200);assert.equal(payments.length,manualBefore+1);assert.equal(documents.filter(d=>d.kind==='receipt').length,receiptBefore+1);assert.equal(await page.getByLabel('Montant partiel ou solde').inputValue(),'');await page.getByLabel('Montant partiel ou solde').fill('5');await page.getByRole('button',{name:'Confirmer la réception fictive',exact:true}).click();await page.waitForTimeout(200);assert.equal(payments.length,manualBefore+2);passed.push('manual receipt committed response lost reload exact replay and next payment without duplicates');
 for(const [state,label] of [['requires_action','Authentification supplémentaire requise'],['processing','Paiement en traitement'],['requires_payment_method','Carte requise ou paiement refusé'],['canceled','Paiement annulé']]){pending={id:'attempt-state',state,amount:10,resolved:state==='canceled'};await go('/me/accounts/folio-demo');await page.getByRole('status').filter({hasText:label}).waitFor();passed.push('payment UI state '+state);}pending=null;
 await page.setViewportSize({width:1365,height:900});await go('/associations/org-demo/shows/show-demo/entries?shell=1');await page.getByRole('navigation',{name:'Concours sélectionné'}).waitFor();await page.screenshot({path:'.tmp/billing-ui/navigation-desktop.png',fullPage:true});passed.push('actual Dashboard mounts existing entries view under contextual navigation');
 for(const section of ['reservations','schedule']){await go('/associations/org-demo/shows/show-demo/'+section+'?shell=1');await page.getByRole('navigation',{name:'Concours sélectionné'}).waitFor();}passed.push('existing reservations and schedule views mount through direct URLs');
 await page.getByLabel('Show actuel').selectOption('show-second');await page.waitForTimeout(100);assert(page.url().includes('/shows/show-second/schedule'));passed.push('show selector preserves equivalent section in canonical URL');
 await go('/associations/org-demo/shows/unknown-show/entries?shell=1');await page.getByRole('alert').filter({hasText:'Concours indisponible ou non autorisé'}).waitFor();passed.push('invalid explicit show never falls back to another business screen');
 pdfState='failed';await go('/me/accounts/folio-demo');await page.getByRole('button',{name:/Facture finale/}).click();await page.getByText('Échec de génération',{exact:true}).waitFor();await page.getByRole('button',{name:'Reprendre la génération',exact:true}).click();await page.getByText('Document PDF disponible',{exact:true}).waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger PDF FR',exact:true}).click();await (await download).saveAs('.tmp/billing-ui/downloaded.pdf');assert(readFileSync('.tmp/billing-ui/downloaded.pdf').subarray(0,4).equals(Buffer.from('%PDF')));passed.push('PDF failed -> retry -> available -> download real fixture bytes (API mocked)');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.tmp/billing-ui/pdf-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));passed.push('PDF controls mobile without horizontal overflow');
 assert.deepEqual(errors,[]);complete=true;
}finally{writeFileSync('.tmp/billing-ui/results.json',JSON.stringify({complete,mode:'browser with RPC/Stripe mocks; no real Stripe calls',passed},null,2));await browser.close();await vite.close();}
