import assert from 'node:assert/strict';
import executable from '@sparticuz/chromium';import {chromium} from 'playwright-core';import {readFileSync,writeFileSync} from 'node:fs';
const state=JSON.parse(readFileSync('.tmp/hsp-direct/integrated.json')),access=JSON.parse(readFileSync('.tmp/hsp-direct/access.local.json'));const stage=process.argv[2],amount=process.argv[3]??'200';const caseName=process.argv[4];if(caseName)state.folio=JSON.parse(readFileSync('.tmp/hsp-direct/cases.json')).cases[caseName].folio;const fixture=JSON.parse(readFileSync('.tmp/hsp-direct/fixture.json'));const admin=stage.startsWith('admin-')||stage==='manual-lost';
process.on('unhandledRejection',()=>{console.error('PILOT_BROWSER_ASYNC_FAILURE: raw diagnostic suppressed');process.exitCode=1;});
assert(['admin-extra','admin-ready','inspect','pay','decline','authenticate','resume-auth','documents','finalize'].includes(stage),'Stage not yet adapted for HSP prototype');
const browser=await chromium.launch({executablePath:await executable.executablePath(),headless:true,args:executable.args.filter(a=>!['--single-process','--disable-web-security','--disable-site-isolation-trials'].includes(a)&&!a.startsWith('--disable-features='))});const page=await browser.newPage({locale:'fr-CA',viewport:{width:1365,height:1000}});page.setDefaultTimeout(30000);page.on('pageerror',e=>console.log('PAGE_ERROR',e.message));page.on('requestfailed',r=>{if(new URL(r.url()).hostname.endsWith('stripe.com'))console.log('STRIPE_NETWORK_FAILED',new URL(r.url()).pathname,r.failure()?.errorText);});page.on('request',r=>{if(r.url().includes('/__local-billing/'))console.log('PAYMENT_REQUEST',JSON.stringify({path:new URL(r.url()).pathname,hasBearer:(r.headers().authorization??'').length>40,origin:r.headers().origin,action:r.postDataJSON()?.action}));});page.on('response',async r=>{if(r.url().includes('/__local-billing/')){console.log('PAYMENT_HTTP',r.status());if(r.status()>=400){const b=await r.json();console.log('PAYMENT_CODE',/^BILLING_[A-Z_]+$/.test(b.error)?b.error:'unclassified');}}});
try{
 await page.goto('http://localhost:5174/me/accounts');const email=access.users.find(x=>x.id.endsWith(admin?'003':'004')).email;
 await page.evaluate(async({email,password})=>{const {requireSupabase}=await import('/src/lib/supabase.ts');const r=await requireSupabase().auth.signInWithPassword({email,password});if(r.error)throw Error('LOGIN_FAILED');},{email,password:access.password});
 await page.goto('http://localhost:5174'+(admin?'/associations/'+fixture.org+'/finance/accounts/':'/me/accounts/')+state.folio);await page.getByRole('heading').filter({hasText:'DEMO-ACC'}).waitFor();await page.getByRole('button',{name:'FR',exact:true}).click();
 if(stage==='admin-extra'){
 const existing=await page.getByRole('cell',{name:/Frais supplémentaire fictif/}).count();if(!existing){await page.getByLabel('Produit — prix du contexte').selectOption(fixture.products[6].id);await page.getByRole('button',{name:'Ajouter le frais',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:/^Confirmer/}).click();await page.getByRole('cell',{name:/Frais supplémentaire fictif/}).waitFor();}await page.screenshot({path:'.tmp/hsp-direct/admin-extra.png',fullPage:true});console.log('Extra sale visible in actual secretary UI');
 }else if(stage==='admin-ready'){await page.getByRole('button',{name:'Attester : tous les frais attendus sont ajoutés',exact:true}).click();await page.getByRole('button',{name:'Retirer l’attestation',exact:true}).waitFor();await page.screenshot({path:'.tmp/hsp-direct/admin-ready.png',fullPage:true});console.log('Readiness granted through actual secretary UI');
 }else if(['inspect','pay','decline','authenticate'].includes(stage)){
  const resume=page.getByRole('button',{name:'Reprendre / vérifier le paiement',exact:true});if(await resume.count())await resume.click();else{await page.getByLabel('Montant partiel ou solde').fill(amount);await page.getByRole('button',{name:'Payer mon compte — TEST',exact:true}).click();}
  await page.frameLocator('iframe[src*="elements-inner-payment"]').locator('input[name="number"]').waitFor({timeout:60000});
  if(stage==='inspect')await page.screenshot({path:'.tmp/hsp-direct/payment-element.png',fullPage:true});
  if(['pay','decline','authenticate'].includes(stage)){
   const frame=page.frames().find(f=>f.url().includes('elements-inner-payment'));if(!frame)throw Error('Payment Element frame absent');
   await frame.locator('input[name="number"]').fill(stage==='decline'?'4000000000000002':stage==='authenticate'?'4000000000003220':'4242424242424242');await frame.locator('input[name="expiry"]').fill('1230');await frame.locator('input[name="cvc"]').fill('123');
   await frame.locator('select[name="country"]').selectOption('CA');const postal=frame.locator('input[name="postalCode"]');if(await postal.count())await postal.fill('H2X 1Y4');
   const response=page.waitForResponse(r=>r.url().includes('/__local-billing/payment')&&r.request().postDataJSON()?.action==='resume',{timeout:90000}).catch(e=>e);await page.getByRole('button',{name:'Confirmer le paiement test',exact:true}).click({trial:true});await page.getByRole('button',{name:'Confirmer le paiement test',exact:true}).focus();await page.getByRole('button',{name:'Confirmer le paiement test',exact:true}).press('Enter');console.log('CONFIRM_CLICKED',await page.getByRole('button',{name:/Confirmer le paiement test|Vérification serveur/}).textContent());if(stage==='authenticate'){let completed=false;for(let i=0;i<90&&!completed;i++){for(const frame of page.frames()){const b=frame.getByRole('button',{name:/^\s*Complete(?: authentication)?\s*$/i});if(await b.count()){await b.click();completed=true;console.log('Actual Stripe 3DS test challenge completed');break;}}if(!completed)await page.waitForTimeout(500);}if(!completed)throw Error('3DS challenge was not completed');}try{const received=await response;if(received instanceof Error)throw received;}catch(e){await page.screenshot({path:'.tmp/hsp-direct/payment-wait.png',fullPage:true});console.log('PAYMENT_WAIT_FRAMES',JSON.stringify(page.frames().map(f=>{try{return new URL(f.url()).hostname;}catch{return 'local';}})));throw e;}await page.waitForTimeout(2000);await page.screenshot({path:'.tmp/hsp-direct/payment-confirmed-'+amount+'-'+(caseName??'main')+'.png',fullPage:true});
   console.log('Payment submitted through real browser Payment Element; server outcome must be checked separately');
  }
 }else if(stage==='resume-auth'){
 await page.getByRole('button',{name:'Reprendre / vérifier le paiement',exact:true}).click();const b=page.getByRole('button',{name:'Poursuivre l’authentification test',exact:true});await b.waitFor();const response=page.waitForResponse(r=>r.url().includes('/__local-billing/payment')&&r.request().postDataJSON()?.action==='resume',{timeout:90000}).catch(e=>e);await b.click({trial:true});await b.focus();await b.press('Enter');let completed=false;for(let i=0;i<90&&!completed;i++){for(const frame of page.frames()){const button=frame.getByRole('button',{name:/^\s*Complete(?: authentication)?\s*$/i});if(await button.count()){await button.click();completed=true;break;}}if(!completed)await page.waitForTimeout(500);}if(!completed){console.log('AUTH_BUTTONS',JSON.stringify(await Promise.all(page.frames().map(f=>f.getByRole('button').allTextContents()))));await page.screenshot({path:'.tmp/hsp-direct/auth-incomplete.png',fullPage:true});throw Error('Authentication test challenge not completed');}const r=await response;if(r instanceof Error)throw r;await page.getByRole('status').filter({hasText:'Paiement confirmé par le serveur'}).waitFor();await page.screenshot({path:'.tmp/hsp-direct/auth-confirmed.png',fullPage:true});console.log('Real Stripe 3DS challenge resumed after reload and completed; HSP server confirmation visible');
 }else if(stage==='documents'){
 const buttons=page.locator('.finance-account > ul').last().getByRole('button');const count=await buttons.count();for(let i=0;i<count;i++){await buttons.nth(i).click();await page.getByRole('button',{name:'Télécharger PDF FR',exact:true}).waitFor({timeout:60000});for(const lang of ['FR','EN']){const download=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger PDF '+lang,exact:true}).click();const file=await download;await file.saveAs('.tmp/hsp-direct/pdf/ui-'+file.suggestedFilename());}}await page.screenshot({path:'.tmp/hsp-direct/payer-document-desktop.png',fullPage:true});await page.reload();await page.getByRole('button',{name:/Facture finale DEMO-INV/}).waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.tmp/hsp-direct/payer-detail-mobile.png',fullPage:true});await page.goto('http://localhost:5174/me/accounts?year=all');await page.getByRole('heading',{name:'Mes comptes',exact:true}).waitFor();await page.screenshot({path:'.tmp/hsp-direct/payer-list-mobile.png',fullPage:true});console.log(JSON.stringify({actualBrowserDownloads:count*2,reload:true,mobile:true}));
 }else if(stage==='manual-lost'){
 let original,deliveries=0;await page.route('**/rest/v1/rpc/record_billing_payment',async route=>{deliveries++;const body=route.request().postDataJSON();if(deliveries===1){original=body;const applied=await fetch('http://127.0.0.1:54321/rest/v1/rpc/record_billing_payment',{method:'POST',headers:route.request().headers(),body:route.request().postData(),signal:AbortSignal.timeout(30000)});assert(applied.ok);await route.abort();}else{if(deliveries===2)assert.deepEqual(body,original);await route.continue();}});
 await page.getByLabel('Montant partiel ou solde').fill('5');await page.getByRole('button',{name:'Confirmer la réception fictive',exact:true}).click();await page.getByRole('button',{name:'Résoudre la commande précédente',exact:true}).waitFor();
 await page.evaluate(async({folio,product})=>{const {billingRpc}=await import('/src/services/billingFolio.ts');const d=await billingRpc('billing_ui_detail',{p_folio:folio,p_personal:false});await billingRpc('add_billing_sale',{p_request_id:crypto.randomUUID(),p_sale:{context_id:d.context.id,payer_customer_account_id:d.payer.customer_account_id,product_id:product,quantity:1,source_id:crypto.randomUUID()}});},{folio:state.folio,product:fixture.products[6].id});
 await page.reload();await page.getByRole('button',{name:'Résoudre la commande précédente',exact:true}).click();await page.getByRole('button',{name:'Résoudre la commande précédente',exact:true}).waitFor({state:'detached'});const counts=()=>page.evaluate(async f=>{const{billingRpc}=await import('/src/services/billingFolio.ts');const d=await billingRpc('billing_ui_detail',{p_folio:f,p_personal:false});return {payments:d.payments.length,receipts:d.documents.filter(x=>x.kind==='receipt').length};},state.folio);assert.deepEqual(await counts(),{payments:1,receipts:1});assert.equal(await page.getByLabel('Montant partiel ou solde').inputValue(),'');await page.getByLabel('Montant partiel ou solde').fill('5');const completed=page.waitForResponse(r=>r.url().endsWith('/rpc/record_billing_payment'));await page.getByRole('button',{name:'Confirmer la réception fictive',exact:true}).click();await completed;assert.deepEqual(await counts(),{payments:2,receipts:2});await page.screenshot({path:'.tmp/hsp-direct/manual-recovered.png',fullPage:true});console.log('Real manual payment committed, response deliberately dropped, fee/version changed, reload and exact original replay: no duplicate; next payment succeeds');
 }else if(stage==='staff-race'){
 assert.equal(process.env.BILLING_SUPABASE_URL,'http://127.0.0.1:54321');const {createClient}=await import('@supabase/supabase-js');const staff=createClient(process.env.BILLING_SUPABASE_URL,process.env.BILLING_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const login=await staff.auth.signInWithPassword({email:access.users.find(u=>u.id.endsWith('003')).email,password:access.password});assert(!login.error);
 await page.route('**/rest/v1/rpc/finalize_own_billing_folio',async route=>{const summary=await staff.rpc('get_billing_statement',{p_folio:state.folio,p_request_id:crypto.randomUUID()});assert(!summary.error);const closed=await staff.rpc('finalize_billing_folio',{p_folio:state.folio,p_request_id:crypto.randomUUID(),p_version:summary.data.account.version,p_statement_id:summary.data.document_id});assert(!closed.error);await route.continue();});
 await page.getByRole('button',{name:'Vérifier le récapitulatif de fermeture',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Finaliser mon compte',exact:true}).click();await page.getByRole('alert').filter({hasText:'BILLING_NOT_ADMISSIBLE'}).first().waitFor();assert.equal(await page.getByRole('button',{name:'Résoudre la commande précédente',exact:true}).count(),0);await page.screenshot({path:'.tmp/hsp-direct/staff-first-refusal.png',fullPage:true});const next=JSON.parse(readFileSync('.tmp/hsp-direct/cases.json')).cases.cancel.folio;await page.goto('http://localhost:5174/me/accounts/'+next);await page.getByLabel('Montant partiel ou solde').fill('5');assert(await page.getByRole('button',{name:'Payer mon compte — TEST',exact:true}).isEnabled());console.log('Real staff-first closure: definitive payer refusal cleared; another account remains usable without a new charge');
 }else if(stage==='finalize'){
  await page.getByRole('button',{name:'Vérifier le récapitulatif de fermeture',exact:true}).click();await page.getByRole('dialog').waitFor();await page.screenshot({path:'.tmp/hsp-direct/recap.png',fullPage:true});await page.getByRole('button',{name:'Finaliser mon compte',exact:true}).click();await page.waitForTimeout(3000);await page.screenshot({path:'.tmp/hsp-direct/finalized.png',fullPage:true});console.log('Finalization submitted through real payer UI');
 }else {await page.screenshot({path:'.tmp/hsp-direct/account.png',fullPage:true});}
 const alerts=await page.getByRole('alert').allTextContents();console.log(JSON.stringify({alerts}));
}catch(e){console.error('PILOT_BROWSER_FAILED',e.name,/^(BILLING_[A-Z_]+|Authentication test challenge not completed)$/.test(e.message)?e.message:'See the last safe stage marker; raw browser diagnostics suppressed');process.exitCode=1;}finally{await browser.close();}
