import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createDocumentWorker,downloadDocument} from '../../server/billing/document-worker.mjs';
function harness(){let state='pending',token=0,arts=[],lost=false,revoked=false;const objects=new Map(),calls=[];const service={storage:{from:()=>({async upload(path,b,opts){assert.equal(opts.upsert,false);assert(!objects.has(path));objects.set(path,b);return {error:null};},async download(path){return {data:new Blob([objects.get(path)])};}})},async rpc(name,a){calls.push(name);if(name==='billing_claim_document'){if(['processing','completed'].includes(state))return {data:null};state='processing';return {data:{document_id:'doc',claim_token:String(++token)}};}if(name==='billing_pdf_source')return {data:{id:'doc',organization_id:'org',snapshot:{}}};if(name==='billing_pdf_complete'){arts=a.p_artifacts;state='completed';if(lost)return {error:{message:'response lost'}};return {data:{state}};}if(name==='billing_finish_document'){if(state==='completed')return {error:{message:'stale'}};state='failed';return {data:{state}};}if(name==='billing_pdf_file')return {data:arts.find(x=>x.locale===a.p_locale)};throw Error(name);}};const user={async rpc(){return revoked?{error:{message:'BILLING_FORBIDDEN'}}:{data:{state}};}};return {service,user,objects,calls,get state(){return state;},set lost(v){lost=v;},set revoked(v){revoked=v;}};}
test('render failure then two workers retry, one publication, no financial writer',async()=>{const h=harness();let fail=true,renders=0;const render=async(d,l)=>{renders++;if(fail&&l==='en'){fail=false;throw Error('render failure');}return Buffer.from('%PDF-'+l);};const a=createDocumentWorker({service:h.service,render}),b=createDocumentWorker({service:h.service,render});assert.equal((await a.run('doc')).state,'failed');const r=await Promise.all([a.run('doc'),b.run('doc')]);assert.equal(r.filter(x=>x.state==='completed').length,1);assert.equal(h.objects.size,3);assert.equal((await a.run()).state,'not_claimed');assert.equal(renders,4);assert(!h.calls.some(x=>/finalize|payment|statement/.test(x)));});
test('download authorizes before IO and after IO, denies other scope',async()=>{const h=harness();await createDocumentWorker({service:h.service,render:async()=>Buffer.from('%PDF-demo')}).run();assert((await downloadDocument({user:h.user,service:h.service,documentId:'doc',locale:'fr'})).toString().startsWith('%PDF'));h.revoked=true;await assert.rejects(downloadDocument({user:h.user,service:h.service,documentId:'doc',locale:'fr'}),/FORBIDDEN/);h.revoked=false;const original=h.service.storage.from;h.service.storage.from=()=>{const b=original();return {...b,async download(p){const r=await b.download(p);h.revoked=true;return r;}};};await assert.rejects(downloadDocument({user:h.user,service:h.service,documentId:'doc',locale:'fr'}),/FORBIDDEN/);});
test('artifact hash mismatch rejected',async()=>{const h=harness();await createDocumentWorker({service:h.service,render:async()=>Buffer.from('%PDF-demo')}).run();for(const k of h.objects.keys())h.objects.set(k,Buffer.from('corrupt'));await assert.rejects(downloadDocument({user:h.user,service:h.service,documentId:'doc',locale:'fr'}),/INTEGRITY/);});
test('lost completion response never reissues document or rerenders completed job',async()=>{const h=harness();h.lost=true;let renders=0;const w=createDocumentWorker({service:h.service,render:async()=>{renders++;return Buffer.from('%PDF');}});await w.run();assert.equal(h.state,'completed');assert.equal((await w.run()).state,'not_claimed');assert.equal(renders,2);assert.equal(h.objects.size,2);});
