// Browser uses real local RPC. Two payments are fictitious manual receipts.
import {createHash} from 'node:crypto';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';import {createClient} from '@supabase/supabase-js';import executable from '@sparticuz/chromium';import {chromium} from 'playwright-core';
const dir='.tmp/review-v5',state=JSON.parse(readFileSync(dir+'/state.json')),f=JSON.parse(readFileSync('.tmp/hsp-direct/fixture.json')),a=JSON.parse(readFileSync('.tmp/hsp-direct/access.local.json')),folio=state.cases.main.folio;
assert.equal(process.env.BILLING_SUPABASE_URL,'http://127.0.0.1:54321');const staff=createClient(process.env.BILLING_SUPABASE_URL,process.env.BILLING_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});assert(!(await staff.auth.signInWithPassword({email:a.users.find(x=>x.id.endsWith('003')).email,password:a.password})).error);
const detail=async()=>{const r=await staff.rpc('billing_ui_detail',{p_folio:folio,p_personal:false});assert(!r.error);return r.data;};
mkdirSync(dir+'/browser-downloads',{recursive:true});const browser=await chromium.launch({downloadsPath:dir+'/browser-downloads',executablePath:await executable.executablePath(),headless:true,args:executable.args.filter(a=>!['--single-process','--disable-web-security','--disable-site-isolation-trials'].includes(a)&&!a.startsWith('--disable-features='))});let page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);
const previous=existsSync(dir+'/browser-results.json')?JSON.parse(readFileSync(dir+'/browser-results.json')):{realBrowser:true,realLocalRPC:true,mockedResponses:false,manualPaymentsSimulated:true,captures:[],checks:[]};const result={...previous,complete:false,captures:[...previous.captures],checks:[...previous.checks]};
async function login(tail){await page.goto('http://localhost:5174/me/accounts?year=all');await page.evaluate(async({email,password})=>{const{requireSupabase}=await import('/src/lib/supabase.ts');if((await requireSupabase().auth.signInWithPassword({email,password})).error)throw Error('LOGIN_FAILED');},{email:a.users.find(x=>x.id.endsWith(tail)).email,password:a.password});}
async function capture(name,element=page){const path=`${dir}/${name}.png`;await element.screenshot({path,...(element===page?{fullPage:true}:{})});result.captures.push(path);}
async function bilingual(name,element=page){for(const locale of ['FR','EN']){await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:locale,exact:true}).click();for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal page overflow');const clipped=await page.locator('.finance-charge-table td').evaluateAll(cs=>cs.filter(c=>c.getBoundingClientRect().width>0&&c.scrollWidth>c.clientWidth+1).length);assert.equal(clipped,0,'Clipped charge cells');await capture(`${name}-${locale.toLowerCase()}-${width}`,element);}}}
try{
 await login('003');await page.goto(`http://localhost:5174/associations/${f.org}/finance/accounts/${folio}`);await page.locator('.finance-charge-groups').first().waitFor();if((await detail()).state==='open')await bilingual('account-open');
 let d=await detail();if(d.state==='open'){
  await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'FR',exact:true}).click();await page.getByRole('button',{name:'Vérifier le récapitulatif de fermeture',exact:true}).click();await page.locator('dialog[open] .finance-document').waitFor();
  // Locale controls are outside the modal; choose each locale before opening it.
  await page.setViewportSize({width:390,height:1000});await capture('closing-recap-fr-390',page.locator('dialog[open]'));await page.setViewportSize({width:1440,height:1000});await capture('closing-recap-fr-1440',page.locator('dialog[open]'));
  await page.getByRole('button',{name:'Fermer et créer la facture finale',exact:true}).click();await page.getByText('Compte fermé — facture finale disponible',{exact:true}).waitFor();d=await detail();
 }
 const invoice=d.documents.find(d=>d.kind==='invoice'),frozen=JSON.stringify(invoice);assert.equal(invoice.snapshot.render_version,5);assert.equal(d.documents.filter(x=>x.kind==='invoice').length,1);
 if(d.balance>0){assert(d.actions.payment);await page.getByRole('button',{name:'FR',exact:true}).click();await page.getByLabel('Montant partiel ou solde').fill(String(d.balance));await capture('closed-payable-staff-1440');await page.getByRole('button',{name:'Confirmer la réception fictive',exact:true}).click();await page.getByLabel('Montant partiel ou solde').waitFor({state:'hidden'});}
 d=await detail();assert.equal(d.balance,0);assert.equal(d.payments.length,2);assert.equal(JSON.stringify(d.documents.find(x=>x.kind==='invoice')),frozen);result.checks.push('Authorized secretary collects closed account; zero balance hides form; final invoice unchanged');
 await page.close();page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);await login('004');await page.goto('http://localhost:5174/me/accounts?year=all');await page.locator('.finance-list').waitFor();await page.locator('.finance-list tbody tr').filter({hasText:d.account_number}).waitFor();await bilingual('my-accounts');result.checks.push('My accounts actually loaded');
 await page.goto('http://localhost:5174/me/accounts/'+folio);await page.locator('.finance-charge-groups').first().waitFor();await bilingual('account-closed');
 for(const kind of ['invoice','statement','receipt']){await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'FR',exact:true}).click();const label={invoice:'Facture finale',statement:'Relevé du compte',receipt:'Reçu de paiement'}[kind];await page.locator('.finance-account > ul').last().getByRole('button').filter({hasText:label}).first().click();await page.locator('.finance-account > .finance-document').waitFor();await bilingual(kind,page.locator('.finance-account > .finance-document'));}
 result.checks.push('FR/EN desktop/mobile account and documents: no horizontal overflow or clipped amount cells');result.captures=[...new Set(result.captures)];result.checks=[...new Set(result.checks)];result.complete=true;
}catch(e){await page.screenshot({path:dir+'/browser-failure.png',fullPage:true});throw e;}finally{await browser.close();writeFileSync(dir+'/browser-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));}
