// Read-only UI checks and downloads of the newly issued fictitious pieces.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {createHash} from 'node:crypto';import executable from '@sparticuz/chromium';import {chromium} from 'playwright-core';
const dir='.tmp/review-v5',a=JSON.parse(readFileSync('.tmp/hsp-direct/access.local.json')),s=JSON.parse(readFileSync(dir+'/state.json')),files=JSON.parse(readFileSync(dir+'/documents-results.json')).files;mkdirSync(dir+'/browser-downloads',{recursive:true});
const browser=await chromium.launch({downloadsPath:dir+'/browser-downloads',executablePath:await executable.executablePath(),headless:true,args:executable.args.filter(a=>!['--single-process','--disable-web-security','--disable-site-isolation-trials'].includes(a)&&!a.startsWith('--disable-features='))}),page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);const result={complete:false,realBrowser:true,mockedResponses:false,captures:[],downloads:0,styleChecks:0};
async function focus(name,root){for(const locale of ['FR','EN']){await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:locale,exact:true}).click();for(const width of [1440,390]){await page.setViewportSize({width,height:1000});const box=root.locator('.finance-ends-bib').first(),styles=await box.evaluate(b=>{const style=s=>getComputedStyle(b.querySelector(s));return {detail:style('.class-detail td:last-child').fontWeight,block:style('.block-total').fontWeight,bib:style('.bib-total').fontWeight,background:style('.bib-total').backgroundColor,border:style('.bib-total').borderTopWidth};});assert.deepEqual(styles,{detail:'600',block:'700',bib:'700',background:'rgb(240, 228, 238)',border:'2px'});result.styleChecks++;const path=`${dir}/focus-${name}-${locale.toLowerCase()}-${width}.png`;await box.screenshot({path});result.captures.push(path);}}}
try{
 await page.goto('http://localhost:5174/me/accounts');await page.evaluate(async({email,password})=>{const {requireSupabase}=await import('/src/lib/supabase.ts');if((await requireSupabase().auth.signInWithPassword({email,password})).error)throw Error('LOGIN_FAILED');},{email:a.users.find(u=>u.id.endsWith('004')).email,password:a.password});await page.goto('http://localhost:5174/me/accounts/'+s.cases.main.folio);await page.locator('.finance-ends-bib').first().waitFor();await focus('account',page.locator('.finance-account > .finance-charge-groups'));
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'FR',exact:true}).click();const buttons=page.locator('.finance-account > ul').last().getByRole('button');assert.equal(await buttons.count(),4);
 for(let i=0;i<4;i++){await buttons.nth(i).click();const doc=page.locator('.finance-account > .finance-document');await doc.waitFor();for(const locale of ['FR','EN']){const event=page.waitForEvent('download');await doc.getByRole('button',{name:new RegExp('^(Télécharger|Download) PDF '+locale+'$')}).click();const download=await event,hash=createHash('sha256').update(readFileSync(await download.path())).digest('hex');assert(files.some(f=>f.locale===locale.toLowerCase()&&f.sha256===hash));result.downloads++;}}
 await buttons.filter({hasText:/Facture finale|Final invoice/}).click();await focus('invoice',page.locator('.finance-account > .finance-document'));result.complete=true;
}finally{await browser.close();writeFileSync(dir+'/focus-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));}
