import {PendingCommands} from './PendingCommands';
import {useEffect,useRef,useState} from 'react';
import {billingRpc,durableRpc,durableStripeKey,observeStripe,pendingStripe,pendingCommands,stripeAction,type Json} from '../../services/billingFolio';
import {DocumentView} from './DocumentView';
import {PaymentElement} from './PaymentElement';
const reasonText:Record<string,[string,string]>={CHECKOUT_DISABLED:['Finalisation autonome non disponible','Self checkout unavailable'],CLOSED:['Compte fermé','Account closed'],CLOSING_PHASE:['Fermeture non encore autorisée','Closing not yet authorized'],FEES_EXPECTED:['D’autres frais sont attendus','More charges expected'],PAYMENT_PENDING:['Une opération est en traitement','An operation is processing'],ADMIN_REVIEW:['Vérification par l’association','Association review'],BALANCE_DUE:['Le solde doit être réglé','Balance must be paid'],BALANCE_REVIEW:['Vérification du solde','Balance review'],PAYER_ONLY:['Seul le payeur peut finaliser','Only the payer can finalize'],RECAP_REQUIRED:['Récapitulatif à confirmer','Review the current summary']};
export function AccountDetail({folio,personal,identity,locale,contacts=[],horses=[]}:{folio:string;personal:boolean;identity:string;locale:string;contacts?:Json[];horses?:Json[]}){
 const fr=locale==='fr',[data,setData]=useState<Json>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[catalog,setCatalog]=useState<Json>(),[doc,setDoc]=useState<Json>(),[recap,setRecap]=useState<Json>(),[attempt,setAttempt]=useState<Json>();
 const draftKey=`hsp-billing-draft:${identity}:${folio}`,modal=useRef<HTMLDialogElement>(null);
 const [form,setForm]=useState(()=>{try{return JSON.parse(sessionStorage.getItem(draftKey)??'null')??{product:'',quantity:'1',amount:'',method:'cash',reference:'',reason:'review',source:crypto.randomUUID()};}catch{return {product:'',quantity:'1',amount:'',method:'cash',reference:'',reason:'review',source:crypto.randomUUID()};}});
 useEffect(()=>{sessionStorage.setItem(draftKey,JSON.stringify(form));},[form,draftKey]);
 useEffect(()=>{const url=new URL(location.href);let changed=false;for(const key of ['payment_intent_client_secret','payment_intent','redirect_status']){if(url.searchParams.has(key)){url.searchParams.delete(key);changed=true;}}if(changed)history.replaceState({},'',url.pathname+url.search);},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(form.amount||form.product){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[form]);
 useEffect(()=>{const leave=(e:MouseEvent)=>{if(!(form.amount||form.product))return;const target=e.target as Element;if(target.closest('nav button, a, [data-finance-back]')&&!window.confirm(fr?'Quitter cette saisie ? Elle restera conservée localement.':'Leave this entry? It will remain saved locally.')){e.preventDefault();e.stopImmediatePropagation();}};document.addEventListener('click',leave,true);return()=>document.removeEventListener('click',leave,true);},[form,fr]);
 const refresh=()=>setRevision(v=>v+1);
 useEffect(()=>{let live=true;setError('');void billingRpc('billing_ui_detail',{p_folio:folio,p_personal:personal}).then(d=>{if(live){setData(d);if(!personal)void billingRpc('billing_ui_catalog',{p_context:d.context.id}).then(c=>{if(live)setCatalog(c);}).catch(e=>setError(e.message));}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[folio,personal,revision]);
 useEffect(()=>{if(recap)modal.current?.showModal();},[recap]);
 async function paymentAction(body:Json){const result=await stripeAction(body);observeStripe(identity,folio,result);return result;}
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const update=(key:string,value:string)=>setForm((v:Json)=>({...v,[key]:value}));
 if(!data)return <div role={error?'alert':'status'}>{error|| (fr?'Chargement du compte…':'Loading account…')}{error&&<button onClick={refresh}>{fr?'Réessayer':'Retry'}</button>}</div>;
 const money=(v:unknown)=>new Intl.NumberFormat(locale,{style:'currency',currency:data.currency}).format(Number(v??0));
 const pending=data.stripe.attempt&&!data.stripe.attempt.resolved;
 return <section className="finance-account"><h2 tabIndex={-1}>{data.account_number} — {locale==='fr'?data.context.name_fr:data.context.name_en}</h2><p>{data.payer.first_name} {data.payer.last_name} · {data.payer.company_name}</p><p>{data.state==='open'?(fr?'Ouvert':'Open'):(fr?'Fermé':'Closed')} · {data.checkout.ready?(fr?'Prêt à finaliser':'Ready to finalize'):(fr?'Frais non attestés complets':'Charges not attested complete')}</p>
 <PendingCommands identity={identity} locale={locale} onResolved={(name,result)=>{if(name==='record_billing_payment')setForm((v:Json)=>({...v,amount:'',reference:'',received_at:null}));if(name==='add_billing_sale')setForm((v:Json)=>({...v,product:'',source:crypto.randomUUID()}));if(result.document?.snapshot?.folio_id===folio)setDoc(result.document);refresh();}}/>
 <strong>{fr?'Solde actuel':'Current balance'} : {money(data.balance)}</strong><p>{fr?'Disponible pour encaissement manuel':'Available for manual payment'} : {money(data.stripe.available)} · {fr?'Réservé':'Reserved'} : {money(data.stripe.reserved)}</p>
 {error&&<p role="alert">{error} — {fr?'Les saisies sont conservées.':'Your entries are retained.'}</p>}
 {data.stripe.attempt&&<p role="status">Stripe TEST : {({preparing:fr?'Préparation':'Preparing',requires_action:fr?'Authentification supplémentaire requise':'Additional authentication required',requires_payment_method:fr?'Carte requise ou paiement refusé':'Card required or payment declined',requires_confirmation:fr?'Prêt à payer':'Ready to pay',processing:fr?'Paiement en traitement':'Payment processing',succeeded:fr?'Paiement confirmé par le serveur':'Payment confirmed by server',canceled:fr?'Paiement annulé':'Payment canceled',anomaly:fr?'Vérification administrative requise':'Administrative review required'} as Record<string,string>)[data.stripe.attempt.state]}</p>}
 <div className="finance-table-wrap"><table><thead><tr><th>{fr?'Frais / bénéficiaire / cheval':'Charge / beneficiary / horse'}</th><th>{fr?'Prix × quantité':'Price × quantity'}</th><th>Taxes</th><th>Total</th></tr></thead><tbody>{data.charges.map((c:Json)=><tr key={c.id}><td>{c.description}<small>{c.beneficiary?.display_name} · {c.horse?.name}</small></td><td>{money(c.unit_price)} × {c.quantity}</td><td>{c.taxes.map((t:Json)=><div key={t.code}>{t.name} {t.rate}% : {money(t.amount)}</div>)}{!c.taxes.length&&c.exemption_reason}</td><td>{money(c.total)}</td></tr>)}</tbody></table></div>
 <p>{fr?'Sous-total':'Subtotal'} : {money(data.subtotal)} · Taxes : {money(data.tax_amount)} · Total : {money(data.total)}</p><h3>{fr?'Paiements reçus':'Payments received'}</h3><ul>{data.payments.map((p:Json)=><li key={p.id}>{p.method} · {money(p.amount)} · {p.received_at}</li>)}</ul>
 {!personal&&data.actions.sale&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await durableRpc(identity,'add_billing_sale',{p_sale:{context_id:data.context.id,payer_customer_account_id:data.payer.customer_account_id,product_id:form.product,quantity:Number(form.quantity),source_id:form.source,...(form.beneficiary?{beneficiary_contact_id:form.beneficiary}:{}),...(form.horse?{horse_id:form.horse}:{})}});setForm((v:Json)=>({...v,product:'',source:crypto.randomUUID()}));});}}><h3>{fr?'Ajouter une vente':'Add sale'}</h3><label>{fr?'Produit — prix du contexte':'Product — context price'}<select required value={form.product} onChange={e=>update('product',e.target.value)}><option value="">—</option>{catalog?.products.map((p:Json)=><option value={p.id} key={p.id}>{p.name} · {money(p.price)}</option>)}</select></label><label>{fr?'Quantité':'Quantity'}<input type="number" required min="0.001" step="0.001" value={form.quantity} onChange={e=>update('quantity',e.target.value)}/></label><label>{fr?'Bénéficiaire (facultatif)':'Beneficiary (optional)'}<select value={form.beneficiary??''} onChange={e=>update('beneficiary',e.target.value)}><option value="">{fr?'Payeur':'Payer'}</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select></label><label>{fr?'Cheval (facultatif)':'Horse (optional)'}<select value={form.horse??''} onChange={e=>update('horse',e.target.value)}><option value="">—</option>{horses.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><button disabled={busy||pendingCommands(identity).length>0}>{fr?'Ajouter le frais':'Add charge'}</button></form>}
 {((personal&&data.stripe.can_pay&&!pending)||(!personal&&data.actions.payment))&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{if(personal){setAttempt(await paymentAction({action:'begin',folio_id:folio,amount:form.amount,request_id:durableStripeKey(identity,folio,form.amount)}));}else{let remaining=Number(form.amount);const allocations=data.charges.flatMap((c:Json)=>{const used=data.payments.flatMap((p:Json)=>p.allocations).filter((a:Json)=>a.charge_id===c.id).reduce((sum:number,a:Json)=>sum+Number(a.amount),0);const amount=Math.round(Math.min(remaining,Number(c.total)-used)*100)/100;remaining=Math.round((remaining-amount)*100)/100;return amount>0?[{charge_id:c.id,amount}]:[];});await durableRpc(identity,'record_billing_payment',{p_payment:{folio_id:folio,version:data.checkout.version,amount:Number(form.amount),method:form.method,reference:form.reference,received_at:form.received_at??new Date().toISOString(),confirmed:true,allocations}});setForm((v:Json)=>({...v,amount:'',reference:'',received_at:null}));}});}}><h3>{personal?(fr?'Payer mon compte':'Pay my account'):(fr?'Encaissement manuel fictif':'Simulated manual payment')}</h3><label>{fr?'Montant partiel ou solde':'Partial amount or balance'}<input required type="number" step="0.01" min="0.01" max={data.stripe.available} value={form.amount} onChange={e=>setForm((v:Json)=>({...v,amount:e.target.value,received_at:v.received_at??new Date().toISOString()}))}/></label>{!personal&&<><label>{fr?'Moyen':'Method'}<select value={form.method} onChange={e=>update('method',e.target.value)}><option value="cash">{fr?'Comptant':'Cash'}</option><option value="etransfer">Interac</option></select></label><label>{fr?'Référence':'Reference'}<input required={form.method==='etransfer'} value={form.reference} onChange={e=>update('reference',e.target.value)}/></label></>}<button disabled={busy||pendingCommands(identity).length>0}>{personal?(fr?'Payer mon compte — TEST':'Pay my account — TEST'):(fr?'Confirmer la réception fictive':'Confirm simulated receipt')}</button></form>}
 {personal&&!data.stripe.can_pay&&data.state==='open'&&Number(data.balance)>0&&!pending&&<p role="status">{fr?'Paiement Stripe test non disponible pour ce compte. Contactez l’association.':'Stripe test payment is unavailable for this account. Contact the association.'}</p>}
 {personal&&!pending&&pendingStripe(identity,folio)&&<button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(async()=>{const original=pendingStripe(identity,folio);setAttempt(await paymentAction({action:'begin',folio_id:folio,amount:original.amount,request_id:original.id}));})}>{fr?'Résoudre la tentative précédente':'Resolve previous payment attempt'}</button>}
 {personal&&pending&&<div className="finance-actions"><button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(async()=>setAttempt(await paymentAction({action:'resume',attempt_id:data.stripe.attempt.id})))}>{fr?'Reprendre / vérifier le paiement':'Resume / check payment'}</button><button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(async()=>{await paymentAction({action:'cancel',attempt_id:data.stripe.attempt.id});setAttempt(undefined);})}>{fr?'Annuler auprès de Stripe':'Cancel with Stripe'}</button></div>}
 {attempt?.client_secret&&<PaymentElement identity={identity} folio={folio} attempt={attempt} locale={locale} onUpdated={()=>{setAttempt(undefined);setForm((v:Json)=>({...v,amount:'',received_at:null}));refresh();}}/>}
 {!personal&&data.actions.attest&&<div className="finance-actions"><button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(()=>billingRpc('billing_set_ready',{p_folio:folio,p_ready:!data.checkout.ready}))}>{data.checkout.ready?(fr?'Retirer l’attestation':'Revoke attestation'):(fr?'Attester : tous les frais attendus sont ajoutés':'Attest: all expected charges are added')}</button><button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(()=>billingRpc('billing_set_close_block',{p_folio:folio,p_key:'administrative_review',p_reason:'review',p_active:true,p_internal_detail:''}))}>{fr?'Bloquer pour vérification':'Block for review'}</button><button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(()=>billingRpc('billing_set_close_block',{p_folio:folio,p_key:'administrative_review',p_reason:'review',p_active:false,p_internal_detail:''}))}>{fr?'Lever la vérification administrative':'Clear administrative review'}</button></div>}
 <ul>{data.checkout.reasons.map((r:string,i:number)=><li key={i}>{reasonText[r]?.[fr?0:1]??r}</li>)}</ul>
 <div className="finance-actions">{!personal&&<button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(async()=>{const r=await durableRpc(identity,'get_billing_statement',{p_folio:folio});setDoc(r.document);})}>{fr?'Produire un relevé':'Create statement'}</button>}
 {((personal&&data.checkout.can_prepare)||(!personal&&data.actions.finalize))&&<button disabled={busy||Boolean(pending)||pendingCommands(identity).length>0} onClick={()=>void run(async()=>{const r=await durableRpc(identity,personal?'prepare_own_billing_recap':'get_billing_statement',{p_folio:folio});setRecap(r);})}>{fr?'Vérifier le récapitulatif de fermeture':'Review closing summary'}</button>}</div>
 <h3>{fr?'Documents':'Documents'}</h3><ul>{data.documents.map((d:Json)=><li key={d.id}><button onClick={()=>setDoc(d)}>{d.kind==='invoice'?(fr?'Facture finale':'Final invoice'):d.kind==='receipt'?(fr?'Reçu de paiement':'Payment receipt'):(fr?'Relevé du compte':'Account statement')} {d.number??new Date(d.created_at).toLocaleString(locale)}</button></li>)}</ul>{doc&&<DocumentView document={doc} locale={locale}/>}
 <dialog ref={modal} onCancel={()=>setRecap(undefined)}>{recap&&<><DocumentView document={recap.document} locale={locale}/><p>{fr?'Confirmez les frais, les taxes et les paiements. La facture finale sera immuable.':'Confirm charges, taxes and payments. The final invoice will be immutable.'}</p><button autoFocus onClick={()=>{modal.current?.close();setRecap(undefined);}}>{fr?'Retour':'Back'}</button><button disabled={busy||pendingCommands(identity).length>0} onClick={()=>void run(async()=>{const version=recap.version??recap.account.version;const r=await durableRpc(identity,personal?'finalize_own_billing_folio':'finalize_billing_folio',personal?{p_folio:folio,p_version:version,p_recap_id:recap.document_id}:{p_folio:folio,p_version:version,p_statement_id:recap.document_id});setDoc(r.document);modal.current?.close();setRecap(undefined);})}>{personal?(fr?'Finaliser mon compte':'Finalize my account'):(fr?'Fermer et créer la facture finale':'Close and create final invoice')}</button>{error&&<p role="alert">{error}</p>}</>}</dialog>
 </section>;
}
