import {useEffect,useState} from 'react';
import {requireSupabase} from '../../lib/supabase';
import type {Json} from '../../services/billingFolio';
export function DocumentPdf({documentId,personal,locale}:{documentId:string;personal:boolean;locale:string}){
 const fr=locale==='fr',[status,setStatus]=useState<Json>(),[error,setError]=useState(false),[busy,setBusy]=useState(false);
 async function request(action:string,lang=locale){const {data}=await requireSupabase().auth.getSession();const r=await fetch('/__local-billing-documents/'+action,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token??''}`},body:JSON.stringify({documentId,personal,locale:lang})});if(!r.ok)throw Error('PDF unavailable');return r;}
 useEffect(()=>{let live=true;setStatus(undefined);setError(false);const refresh=async()=>{try{const r=await request('status');const s=await r.json();if(live){setStatus(s);setError(false);}}catch{if(live)setError(true);}};void refresh();const t=setInterval(()=>void refresh(),5000);return()=>{live=false;clearInterval(t);};},[documentId,personal]);
 async function action(kind:string,lang:string){setBusy(true);setError(false);let tab:Window|null=null;try{if(kind==='view'){tab=window.open('','_blank');if(tab)tab.opener=null;}const r=await request(kind==='retry'?'retry':'download',lang);if(kind==='retry')setStatus(await r.json());else{const url=URL.createObjectURL(await r.blob());if(tab)tab.location.href=url;else{const a=document.createElement('a');a.href=url;a.download=`HSP-${documentId}-${lang}.pdf`;a.click();}setTimeout(()=>URL.revokeObjectURL(url),60000);}}catch{tab?.close();setError(true);}finally{setBusy(false);}}
 const labels:Record<string,[string,string]>={pending:['Génération en attente','Generation pending'],processing:['Génération en cours','Generation in progress'],failed:['Échec de génération','Generation failed'],completed:['Document PDF disponible','PDF available'],unavailable:['PDF indisponible pour cette pièce','PDF unavailable for this document']};
 return <section aria-label={fr?'Documents PDF':'PDF documents'}>{error?<p role="alert">{fr?'Service PDF indisponible. La pièce financière reste conservée.':'PDF service unavailable. The financial document remains saved.'}</p>:<p role="status">{status?(labels[status.state]??labels.unavailable)[fr?0:1]:(fr?'Vérification du PDF…':'Checking PDF…')}</p>}
 {status?.state==='completed'&&['fr','en'].map(lang=><span key={lang}><button disabled={busy} onClick={()=>void action('view',lang)}>{fr?'Consulter':'View'} PDF {lang.toUpperCase()}</button><button disabled={busy} onClick={()=>void action('download',lang)}>{fr?'Télécharger':'Download'} PDF {lang.toUpperCase()}</button></span>)}
 {status&&['pending','failed'].includes(status.state)&&<button disabled={busy||(status.retry_at&&Date.parse(status.retry_at)>Date.now())} onClick={()=>void action('retry',locale)}>{fr?'Reprendre la génération':'Retry generation'}</button>}</section>;
}
