import {PendingCommands} from './PendingCommands';
import {useEffect,useState,type ReactNode} from 'react';
import {billingRpc,durableRpc,type Json} from '../../services/billingFolio';
import {AccountDetail} from './AccountDetail';
import {financeRoute,navigateBilling} from './navigation';
import './finance.css';
export function FinanceView({org,show='',personal=false,identity,locale,legacy,contacts=[],organizations=[],horses=[]}:{org:string;show?:string;personal?:boolean;identity:string;locale:string;legacy:ReactNode;contacts?:Json[];organizations?:Json[];horses?:Json[]}){
 const fr=locale==='fr';const [url,setUrl]=useState(()=>new URL(window.location.href));const [result,setResult]=useState<Json>(),[error,setError]=useState(''),[revision,setRevision]=useState(0),[catalog,setCatalog]=useState<Json>();
 const firstKey=`hsp-first-sale:${identity}:${org}:${show||new URL(location.href).searchParams.get('context')||''}`;
 const initial=()=>{try{return JSON.parse(sessionStorage.getItem(firstKey)??'{}');}catch{return {};}};
 const [payer,setPayer]=useState(()=>initial().payer??''),[product,setProduct]=useState(()=>initial().product??''),[busy,setBusy]=useState(false),[source,setSource]=useState(()=>initial().source??crypto.randomUUID());
 useEffect(()=>{sessionStorage.setItem(firstKey,JSON.stringify({payer,product,source}));},[firstKey,payer,product,source]);
 useEffect(()=>{const onPop=()=>setUrl(new URL(window.location.href));window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
 const params=url.searchParams,year=params.get('year')??(show?'all':String(new Date().getFullYear())),tab=params.get('tab')??'overview',context=params.get('context')??'',query=params.get('q')??'',offset=Number(params.get('offset')??0),state=params.get('state')??'',folio=financeRoute(url.pathname)?.folio??'';
 const patch=(values:Record<string,string>)=>{const next=new URL(window.location.href);Object.entries(values).forEach(([k,v])=>v?next.searchParams.set(k,v):next.searchParams.delete(k));if(!('offset'in values))next.searchParams.delete('offset');navigateBilling(next.pathname+next.search);};
 useEffect(()=>{if(folio||(!personal&&!org))return;let live=true;setResult(undefined);setError('');const filter={...(year!=='all'?{year:Number(year)}:{}),...(state?{state}:{}),...(params.get('type')?{type_id:params.get('type')}:{}),...(params.get('show')?{show_id:params.get('show')}:{}),...(query?{q:query}:{}),...(show?{show_id:show}:{}),...(context?{context_id:context}:{}),...(params.get('prior')?{prior_balance:true}:{})};
 const task=personal?billingRpc('list_my_billing_accounts',{p_org:params.get('org')||null,p_filter:filter,p_limit:25,p_offset:offset}):show||context?billingRpc('list_billing_accounts',{p_org:org,p_filter:filter,p_limit:25,p_offset:offset}):query?billingRpc('search_billing_finance',{p_org:org,p_query:query,p_year:year==='all'?null:Number(year),p_limit:25,p_offset:offset}):tab==='overview'?billingRpc('get_billing_finance_overview',{p_org:org,p_year:year==='all'?null:Number(year)}):billingRpc('list_billing_contexts',{p_org:org,p_kind:tab==='shows'?'event':'non_event',p_year:year==='all'?null:Number(year),p_limit:25,p_offset:offset});
 void task.then(d=>{if(live)setResult(d);}).catch(e=>{if(live)setError(e.message);});
 if(show&&!context&&!personal)void billingRpc('list_billing_contexts',{p_org:org,p_kind:'event',p_year:null,p_limit:100,p_offset:0}).then(d=>{const c=d.items.find((r:Json)=>r.show_id===show);if(c?.id)return billingRpc('billing_ui_catalog',{p_context:c.id});}).then(c=>{if(live)setCatalog(c);}).catch(e=>{if(live)setError(e.message);});
 if(context&&!personal)void billingRpc('billing_ui_catalog',{p_context:context}).then(c=>{if(live)setCatalog(c);}).catch(e=>{if(live)setError(e.message);});else setCatalog(undefined);
 return()=>{live=false;};},[org,show,personal,url.href,revision,folio]);
 const openAccount=(id:string)=>{const next=new URLSearchParams(url.search);if(show){next.set('return_show',show);if(!next.has('year'))next.set('year','all');}navigateBilling(`${personal?'/me/accounts':`/associations/${org}/finance/accounts`}/${id}?${next}`);};
 if(!personal&&!org)return <p>{fr?'Sélectionnez une association autorisée.':'Select an authorized association.'}</p>;
 return <section className="finance"><div className="finance-demo" role="note">{fr?'DÉMONSTRATION — données fictives · Stripe TEST uniquement':'DEMONSTRATION — fictitious data · Stripe TEST only'}</div><h2>{personal?(fr?'Mes comptes':'My accounts'):show?(fr?'Comptes du concours':'Show accounts'):'Finance'}</h2>
 {!folio&&<PendingCommands identity={identity} locale={locale} onResolved={(name)=>{if(name==='add_billing_sale'){setProduct('');setSource(crypto.randomUUID());}setRevision(v=>v+1);}}/>}
 {folio?<><button data-finance-back onClick={()=>navigateBilling(`${personal?'/me/accounts':params.get('return_show')?`/associations/${org}/shows/${params.get('return_show')}/accounts`:`/associations/${org}/finance`}${url.search}`)}>{fr?'Retour à la liste':'Back to list'}</button><AccountDetail key={folio+personal} folio={folio} personal={personal} identity={identity} locale={locale} contacts={contacts} horses={horses}/></>:<>
 <div className="finance-filters"><label>{fr?'Année':'Year'}<select value={year} onChange={e=>patch({year:e.target.value})}><option value="all">{fr?'Toutes les années':'All years'}</option>{Array.from({length:16},(_,i)=>new Date().getFullYear()+2-i).map(y=><option key={y}>{y}</option>)}</select></label><label>{fr?'Recherche':'Search'}<input type="search" value={query} onChange={e=>patch({q:e.target.value})}/></label><label>{fr?'État':'State'}<select value={state} onChange={e=>patch({state:e.target.value})}><option value="">{fr?'Tous':'All'}</option><option value="open">{fr?'Ouverts':'Open'}</option><option value="closed">{fr?'Fermés':'Closed'}</option></select></label>{personal&&<label>{fr?'Association':'Association'}<select value={params.get('org')??''} onChange={e=>patch({org:e.target.value})}><option value="">{fr?'Toutes':'All'}</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}{personal&&<button onClick={()=>patch({year:'all',prior:params.get('prior')?'':'true'})}>{fr?'Soldes des années précédentes':'Prior-year balances'} {params.get('prior')?'✓':''}</button>}</div>
 {!personal&&!show&&<nav className="finance-tabs" aria-label="Finance">{[['overview',fr?'Vue d’ensemble':'Overview'],['shows',fr?'Concours':'Shows'],['outside',fr?'Comptes hors concours':'Non-show accounts']].map(([k,label])=><button aria-current={tab===k?'page':undefined} key={k} onClick={()=>patch({tab:k,context:'',q:''})}>{label}</button>)}</nav>}
 {context&&<button onClick={()=>patch({context:''})}>{fr?'Tous les contextes':'All contexts'}</button>}
 {error?<div role="alert">{error}<button onClick={()=>setRevision(v=>v+1)}>{fr?'Réessayer':'Retry'}</button></div>:!result?<p role="status">{fr?'Chargement…':'Loading…'}</p>:<>
 {result.groups&&<div className="finance-metrics">{!result.has_data?<p>{fr?'Aucune donnée pour cette année.':'No data for this year.'}</p>:result.groups.map((g:Json)=><article key={g.currency}><h3>{g.currency}</h3><dl>{[['subtotal',fr?'Frais hors taxes':'Subtotal'],['tax_amount','Taxes'],['paid',fr?'Paiements reçus':'Payments received'],['balance',fr?'Solde à recevoir':'Receivable'],['open_accounts',fr?'Comptes ouverts':'Open accounts'],['closed_accounts',fr?'Comptes fermés':'Closed accounts'],['needs_attention',fr?'Interventions':'Needs attention']].map(([k,label])=><div key={k}><dt>{label}</dt><dd>{g[k]}</dd></div>)}</dl></article>)}</div>}
 {result.items&&<>{!result.items.length?<p>{fr?'Aucun résultat autorisé dans cette sélection.':'No authorized results in this selection.'}</p>:<div className="finance-table-wrap"><table className="finance-list"><thead><tr><th>{fr?'Compte / contexte':'Account / context'}</th><th>{fr?'Payeur / dates':'Payer / dates'}</th><th>{fr?'État / comptes ouverts':'State / open accounts'}</th><th>{fr?'Frais / paiements / solde':'Charges / paid / balance'}</th><th/></tr></thead><tbody>{result.items.map((r:Json)=><tr key={r.id??r.show_id}><td>{r.account_number??r.number??(fr?r.name_fr:r.name_en)}<small>{({show_account:fr?'Compte du concours':'Show account',non_event_account:fr?'Compte hors concours':'Non-show account',statement:fr?'Relevé':'Statement',receipt:fr?'Reçu de paiement':'Payment receipt',invoice:fr?'Facture finale':'Final invoice'} as Record<string,string>)[r.kind]??''} · {r.year??'—'}</small></td><td>{r.payer?[r.payer.first_name,r.payer.last_name,r.payer.company_name].filter(Boolean).join(' '):`${r.start_date??''} ${r.end_date??''}`}</td><td>{r.state==='open'?(fr?'Ouvert':'Open'):r.state==='closed'?(fr?'Fermé':'Closed'):r.status??r.open_accounts}</td><td>{r.total??'—'} / {r.paid??'—'} / {r.balance??'—'} {r.currency}</td><td>{r.account_number?<button onClick={()=>openAccount(r.account_id??r.id)}>{fr?'Ouvrir':'Open'}</button>:r.id?<button onClick={()=>patch({context:r.id})}>{fr?'Voir les comptes':'View accounts'}</button>:<span>{fr?'Moteur historique — non adopté':'Legacy engine — not adopted'}</span>}</td></tr>)}</tbody></table></div>}<div className="finance-actions"><button disabled={offset===0} onClick={()=>patch({offset:String(Math.max(0,offset-25))})}>{fr?'Précédent':'Previous'}</button><span>{offset+1}–{Math.min(offset+25,result.total)} / {result.total}</span><button disabled={offset+25>=result.total} onClick={()=>patch({offset:String(offset+25)})}>{fr?'Suivant':'Next'}</button></div></>}
 </>}
 {!personal&&catalog?.enabled&&<form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void (async()=>{const customer=await billingRpc('billing_get_customer_account',{p_org:org,p_contact:payer,p_context:catalog.context_id});await durableRpc(identity,'add_billing_sale',{p_sale:{context_id:catalog.context_id,payer_customer_account_id:customer,product_id:product,quantity:1,source_id:source}});setSource(crypto.randomUUID());setRevision(v=>v+1);})().catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><h3>{fr?'Première vente à un client':'First sale to a client'}</h3><label>{fr?'Payeur officiel':'Official payer'}<select required value={payer} onChange={e=>setPayer(e.target.value)}><option value="">—</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name} {c.company_name}</option>)}</select></label><label>{fr?'Produit':'Product'}<select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">—</option>{catalog.products.map((p:Json)=><option key={p.id} value={p.id}>{p.name} · {p.price} {catalog.currency}</option>)}</select></label><button disabled={busy}>{fr?'Ajouter au bon compte':'Add to the payer account'}</button></form>}
 <details><summary>{fr?'Facturation historique (legacy)':'Historical billing (legacy)'}</summary>{legacy}</details>
 </>}
 </section>;
}
