import type {Json} from '../../services/billingFolio';
export const closedLabel=(locale:string)=>locale==='fr'?'Compte fermé — facture finale disponible':'Account closed — final invoice available';
export function paymentLabel(method:string,locale:string){const fr=locale==='fr';return ({cash:fr?'Comptant':'Cash',etransfer:fr?'Virement Interac':'Interac transfer',stripe_test:fr?'Carte bancaire (test)':'Card (test)'})[method]??(fr?'Paiement':'Payment');}
export function paymentDate(value:string,locale:string){const date=new Date(value);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat(locale==='fr'?'fr-CA':'en-CA',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(date)+' UTC';}
export const reasonText:Record<string,[string,string]>={CHECKOUT_DISABLED:['Finalisation autonome non disponible','Self checkout unavailable'],CLOSED:['Compte fermé — facture finale disponible','Account closed — final invoice available'],CLOSING_PHASE:['La période de fermeture n’est pas encore ouverte.','The closing period is not open yet.'],FEES_EXPECTED:['L’association attend encore des frais.','The association is still expecting charges.'],PAYMENT_PENDING:['Un paiement est en traitement. Vérifiez son état avant de finaliser.','A payment is processing. Check its status before finalizing.'],ADMIN_REVIEW:['L’association doit terminer la vérification du compte.','The association must finish reviewing this account.'],BALANCE_DUE:['Réglez le solde avant de finaliser.','Pay the balance before finalizing.'],BALANCE_REVIEW:['Le solde doit être vérifié par l’association.','The association must review the balance.'],PAYER_ONLY:['Seul le payeur peut finaliser ce compte.','Only the payer can finalize this account.'],RECAP_REQUIRED:['Récapitulatif à confirmer','Review the current summary']};
export function billingError(message:string,locale:string,data?:Json){
 const fr=locale==='fr';
 if(message.includes('billing_etransfer_reference_key'))return fr?'Cette référence Interac a déjà été enregistrée. Vérifiez le paiement existant.':'This Interac reference is already recorded. Check the existing payment.';
 if(data?.state==='closed'&&/BILLING_(NOT_ADMISSIBLE|FOLIO_CLOSED|STALE_RECAP|STALE_VERSION)/.test(message))return closedLabel(locale);
 if(message==='BILLING_NOT_ADMISSIBLE'&&data){const reasons=(data.checkout?.reasons??[]).filter((r:string)=>r!=='RECAP_REQUIRED');if(reasons.length)return reasons.map((r:string)=>reasonText[r]?.[fr?0:1]??(fr?'Contactez l’association pour vérifier ce compte.':'Contact the association to review this account.')).join(' ');}
 const messages:Record<string,[string,string]>={BILLING_STALE_RECAP:['Le compte a changé. Vérifiez un nouveau récapitulatif avant de confirmer.','The account changed. Review a new summary before confirming.'],BILLING_STALE_VERSION:['Le compte a changé. Actualisez les montants avant de réessayer.','The account changed. Refresh the amounts before retrying.'],BILLING_PAYMENT_EXCEEDS_BALANCE:['Le montant dépasse le solde payable.','The amount exceeds the payable balance.'],BILLING_PAYMENT_RESERVED:['Un paiement réserve déjà une partie du solde. Vérifiez le paiement en cours.','A payment already reserves part of the balance. Check the pending payment.'],BILLING_PREVIOUS_COMMAND_UNRESOLVED:['Vérifiez l’opération précédente avant de poursuivre.','Resolve the previous operation before continuing.'],BILLING_FORBIDDEN:['Vous n’avez pas accès à cette opération. Vérifiez votre connexion ou contactez l’association.','You cannot access this operation. Check your login or contact the association.'],BILLING_PENDING_PAYMENT:reasonText.PAYMENT_PENDING,BILLING_BLOCKED:reasonText.ADMIN_REVIEW,BILLING_RECAP_REQUIRED:reasonText.RECAP_REQUIRED,BILLING_STALE_QUOTE:['Les frais ont changé. Vérifiez la nouvelle proposition.','Charges changed. Review the new quote.']};
 return messages[message]?.[fr?0:1]??(fr?'L’opération n’a pas pu être confirmée. Actualisez le compte pour vérifier son état avant de réessayer.':'The operation could not be confirmed. Refresh the account to check its status before retrying.');
}
export function chargeGroups(charges:Json[],locale:string){
 const fr=locale==='fr',groups=new Map<string,{key:string;label:string;entry:boolean;charges:Json[]}>();
 for(const c of charges){const p=c.presentation;const entry=p?.section==='entry'&&c.supplier!=='hsp';const key=c.supplier==='hsp'?'hsp':entry?JSON.stringify([c.horse?.id,p.block_id,p.occurrence_id]):p?.section==='reservation'?'reservation':'other';
 if(!groups.has(key))groups.set(key,{key,entry,label:key==='hsp'?(fr?'Service HSP':'HSP service'):entry?`${fr?'Inscriptions':'Entries'} · ${c.horse?.name??''} · ${p.block_label} · ${p.occurrence_id}`:key==='reservation'?(fr?'Réservations':'Reservations'):(fr?'Autres achats et services':'Other purchases and services'),charges:[]});groups.get(key)!.charges.push(c);}
 return [...groups.values()].sort((a,b)=>(a.entry?0:a.key==='reservation'?1:a.key==='other'?2:3)-(b.entry?0:b.key==='reservation'?1:b.key==='other'?2:3));
}
